services:
  ia-api:
    container_name: ia-api
    build:
      context: ../../ia-api/docker
      dockerfile: dev.Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    volumes:
      - ../../ia-api/app:/usr/src/app
    networks:
      - ia-manager

  ia-worker:
    container_name: ia-worker
    build:
      context: ../../ia-api/docker
      dockerfile: dev.worker.Dockerfile
    restart: always
    volumes:
      - ../../ia-api/app:/usr/src/app
    extra_hosts:
      - "test-site.com:172.19.0.1"
      - "www.latiendanautica.es:172.19.0.1"
      - "latiendanautica.es:172.19.0.1"
    networks:
      - ia-manager

  ia-api-migrations:
    container_name: ia-api-migrations
    build:
      context: ../../ia-api/docker
      dockerfile: migrations.Dockerfile
    volumes:
      - ../../ia-api/app:/usr/src/app
    depends_on:
      - ia-api
    networks:
      - ia-manager

  ia-api-seeders:
    container_name: ia-api-seeders
    build:
      context: ../../ia-api/docker
      dockerfile: seeders.Dockerfile  # puedes crear un Dockerfile específico para seeders si quieres
    volumes:
      - ../../ia-api/app:/usr/src/app
    depends_on:
      - ia-api
    networks:
      - ia-manager