services:
  ia-api:
    container_name: ia-api-checkout
    build:
      context: ../../ia-api/docker
      dockerfile: dev.Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: development
      REDIS_HOST: ia-redis-checkout
    volumes:
      - ../../ia-api/app:/usr/src/app
    networks:
      - traefik_vps_net

  ia-worker:
    container_name: ia-worker-checkout
    build:
      context: ../../ia-api/docker
      dockerfile: dev.worker.Dockerfile
    restart: always
    volumes:
      - ../../ia-api/app:/usr/src/app
    environment:
      NODE_ENV: development
      REDIS_HOST: ia-redis
    extra_hosts:
      - "www.latiendanautica.es:172.19.0.1"
      - "latiendanautica.es:172.19.0.1"
    networks:
      - traefik_vps_net

  ia-api-migrations:
    container_name: ia-api-migrations-checkout
    build:
      context: ../../ia-api/docker
      dockerfile: migrations.Dockerfile
    volumes:
      - ../../ia-api/app:/usr/src/app
    depends_on:
      - ia-api
    networks:
      - traefik_vps_net

  ia-api-seeders:
    container_name: ia-api-seeders-checkout
    build:
      context: ../../ia-api/docker
      dockerfile: seeders.Dockerfile  # puedes crear un Dockerfile específico para seeders si quieres
    volumes:
      - ../../ia-api/app:/usr/src/app
    depends_on:
      - ia-api
    networks:
      - traefik_vps_net